req_section = "new title\ndummy change\ndummy change with updated title\ndummy change with updated title"
[[pull_requests]]
uid = "3"
author_uid = "Bibo-Joshi"
closes_threads = ["1"]

[[pull_requests]]
uid = "4"
author_uid = "Bibo-Joshi"
closes_threads = ["2"]
